AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
  UsEastDefaultSubnetA:
    Type: String
    Default: subnet-3bfa1864
  UsEastDefaultSubnetB:
    Type: String
    Default: subnet-cd799fab


Resources:
  RobinCloudBucket:
    Type: AWS::S3::Bucket

  RobinSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: RobinSQSQueue

  RobinEC2instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType:
        Ref: InstanceTypeParameter

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: [!Ref UsEastDefaultSubnetA, !Ref UsEastDefaultSubnetB]

Outputs:

  LoadBalnseDNS:
    Description: ALB DNS adress
    Value: !GetAtt LoadBalancer.DNSName